# Instalação
- conda install dask
- pip install dask

In [ ]:
#pip install dask

## 1. Dask Arrays

In [1]:
## Import dask Array
import dask.array as da

In [ ]:
x = da.random.random((10000,10000), chunks=(1000,1000))

In [ ]:
x

In [ ]:
x.compute()

# 2. Dask DataFrame

In [ ]:
## import dataset default dask
from dask import datasets

In [ ]:
df = datasets.timeseries()

In [ ]:
df.persist()

In [ ]:
df.compute()

In [ ]:
df.visualize()

# 3. Agendador Dinâmico

### Modo Distribuído 3.1

In [ ]:
from dask.distributed import Client
client = Client() # Set Up local Cluster on your LaptTop
#Client = Client('127.0.0.1:8786')
client

In [ ]:
client.close()

## Análise Vôos no Brasil

### Data Set Kaggle: 
https://www.kaggle.com/ramirobentes/flights-in-brazil

### Tutorial Youtube:
https://youtu.be/Vu4CKemvogQ

### 4.1 Leitura dos Dados

In [2]:
filename = 'home/biolabs/aws/___Publics_Repository/My-Data-Science-Journey/24-Notebooks/Dask/Anac-Voos-Brasil/BrFlights2.csv'

In [3]:
filename = './BrFlights2.csv'

### Versão Utilizando Pandas

In [5]:
import pandas as pd

In [6]:
%%time
df = pd.read_csv(filename, encoding='unicode_escape')

CPU times: user 16.7 s, sys: 2.12 s, total: 18.8 s
Wall time: 23.2 s

In [ ]:
df = pd.read_csv("BrFlights2.csv")

In [ ]:
df = pd.read_csv('BrFlights2.csv', encoding='latin1')

In [7]:
df.head(3)

,Voos,Companhia.Aerea,Codigo.Tipo.Linha,Partida.Prevista,Partida.Real,Chegada.Prevista,Chegada.Real,Situacao.Voo,Codigo.Justificativa,Aeroporto.Origem,...,Estado.Origem,Pais.Origem,Aeroporto.Destino,Cidade.Destino,Estado.Destino,Pais.Destino,LongDest,LatDest,LongOrig,LatOrig
0,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-30T08:58:00Z,2016-01-30T08:58:00Z,2016-01-30T10:35:00Z,2016-01-30T10:35:00Z,Realizado,NaN,Afonso Pena,...,PR,Brasil,Salgado Filho,Porto Alegre,RS,Brasil,-51.175381,-29.993473,-49.172481,-25.532713
1,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-13T12:13:00Z,2016-01-13T12:13:00Z,2016-01-13T21:30:00Z,2016-01-13T21:30:00Z,Realizado,NaN,Salgado Filho,...,RS,Brasil,Miami,Miami,N/I,Estados Unidos,-80.287046,25.795865,-51.175381,-29.993473
2,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-29T12:13:00Z,2016-01-29T12:13:00Z,2016-01-29T21:30:00Z,2016-01-29T21:30:00Z,Realizado,NaN,Salgado Filho,...,RS,Brasil,Miami,Miami,N/I,Estados Unidos,-80.287046,25.795865,-51.175381,-29.993473

In [8]:
df.tail()

,Voos,Companhia.Aerea,Codigo.Tipo.Linha,Partida.Prevista,Partida.Real,Chegada.Prevista,Chegada.Real,Situacao.Voo,Codigo.Justificativa,Aeroporto.Origem,...,Estado.Origem,Pais.Origem,Aeroporto.Destino,Cidade.Destino,Estado.Destino,Pais.Destino,LongDest,LatDest,LongOrig,LatOrig
2542514,UAL - 129,UNITED AIRLINES,Internacional,2015-12-14T01:25:00Z,2015-12-14T04:31:00Z,2015-12-14T11:19:00Z,2015-12-14T14:18:00Z,Realizado,ATRASOS NAO ESPECIFICOS - OUTROS,Houston,...,N/I,Estados Unidos,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.81341,-95.336783,29.99022
2542515,UAL - 129,UNITED AIRLINES,Internacional,2015-12-01T01:25:00Z,2015-12-01T01:25:00Z,2015-12-01T11:19:00Z,2015-12-01T11:19:00Z,Realizado,NaN,Houston,...,N/I,Estados Unidos,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.81341,-95.336783,29.99022
2542516,UAL - 129,UNITED AIRLINES,Internacional,2015-12-27T01:25:00Z,2015-12-27T01:25:00Z,2015-12-27T11:19:00Z,2015-12-27T11:19:00Z,Realizado,NaN,Houston,...,N/I,Estados Unidos,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.81341,-95.336783,29.99022
2542517,UAL - 129,UNITED AIRLINES,Internacional,2015-12-05T01:25:00Z,2015-12-05T01:21:00Z,2015-12-05T11:19:00Z,2015-12-05T10:48:00Z,Realizado,ATRASOS NAO ESPECIFICOS - OUTROS,Houston,...,N/I,Estados Unidos,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.81341,-95.336783,29.99022
2542518,UAL - 129,UNITED AIRLINES,Internacional,2015-12-09T01:25:00Z,2015-12-09T01:25:00Z,2015-12-09T11:19:00Z,2015-12-09T11:19:00Z,Realizado,NaN,Houston,...,N/I,Estados Unidos,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.81341,-95.336783,29.99022

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2542519 entries, 0 to 2542518
Data columns (total 21 columns):
 #   Column                Dtype
---  ------                -----
 0   Voos                  object
 1   Companhia.Aerea       object
 2   Codigo.Tipo.Linha     object
 3   Partida.Prevista      object
 4   Partida.Real          object
 5   Chegada.Prevista      object
 6   Chegada.Real          object
 7   Situacao.Voo          object
 8   Codigo.Justificativa  object
 9   Aeroporto.Origem      object
 10  Cidade.Origem         object
 11  Estado.Origem         object
 12  Pais.Origem           object
 13  Aeroporto.Destino     object
 14  Cidade.Destino        object
 15  Estado.Destino        object
 16  Pais.Destino          object
 17  LongDest              float64
 18  LatDest               float64
 19  LongOrig              float64
 20  LatOrig               float64
dtypes: float64(4), object(17)
memory usage: 407.4+ MB

In [10]:
df.describe()

           LongDest       LatDest      LongOrig       LatOrig
count  2.542519e+06  2.542519e+06  2.542519e+06  2.542519e+06
mean  -4.645362e+01 -1.718682e+01 -4.645216e+01 -1.716691e+01
std    1.051800e+01  1.227153e+01  1.051854e+01  1.227237e+01
min   -1.184085e+02 -5.825304e+01 -1.184085e+02 -5.825304e+01
25%   -4.864909e+01 -2.343455e+01 -4.864909e+01 -2.343455e+01
50%   -4.665658e+01 -2.281341e+01 -4.665658e+01 -2.281341e+01
75%   -4.324942e+01 -1.291110e+01 -4.324942e+01 -1.291110e+01
max    5.536567e+01  5.231054e+01  5.536567e+01  5.231054e+01

### Versão Utilizando Dask

In [4]:
## Import Dask Data Frame
import dask.dataframe as dd

In [5]:
%%time
ddf = dd.read_csv(filename, encoding='unicode_escape')

CPU times: user 12.3 ms, sys: 8.94 ms, total: 21.2 ms
Wall time: 32.9 ms

In [6]:
ddf

Dask DataFrame Structure:
                  Voos Companhia.Aerea Codigo.Tipo.Linha Partida.Prevista Partida.Real Chegada.Prevista Chegada.Real Situacao.Voo Codigo.Justificativa Aeroporto.Origem Cidade.Origem Estado.Origem Pais.Origem Aeroporto.Destino Cidade.Destino Estado.Destino Pais.Destino LongDest  LatDest LongOrig  LatOrig
npartitions=11
                object          object            object           object       object           object       object       object               object           object        object        object      object            object         object         object       object  float64  float64  float64  float64
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
...                ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
Dask Name: read-csv, 11 tasks

In [17]:
ddf.head(3)

,Voos,Companhia.Aerea,Codigo.Tipo.Linha,Partida.Prevista,Partida.Real,Chegada.Prevista,Chegada.Real,Situacao.Voo,Codigo.Justificativa,Aeroporto.Origem,...,Estado.Origem,Pais.Origem,Aeroporto.Destino,Cidade.Destino,Estado.Destino,Pais.Destino,LongDest,LatDest,LongOrig,LatOrig
0,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-30T08:58:00Z,2016-01-30T08:58:00Z,2016-01-30T10:35:00Z,2016-01-30T10:35:00Z,Realizado,NaN,Afonso Pena,...,PR,Brasil,Salgado Filho,Porto Alegre,RS,Brasil,-51.175381,-29.993473,-49.172481,-25.532713
1,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-13T12:13:00Z,2016-01-13T12:13:00Z,2016-01-13T21:30:00Z,2016-01-13T21:30:00Z,Realizado,NaN,Salgado Filho,...,RS,Brasil,Miami,Miami,N/I,Estados Unidos,-80.287046,25.795865,-51.175381,-29.993473
2,AAL - 203,AMERICAN AIRLINES INC,Internacional,2016-01-29T12:13:00Z,2016-01-29T12:13:00Z,2016-01-29T21:30:00Z,2016-01-29T21:30:00Z,Realizado,NaN,Salgado Filho,...,RS,Brasil,Miami,Miami,N/I,Estados Unidos,-80.287046,25.795865,-51.175381,-29.993473

In [18]:
ddf.tail(3)

,Voos,Companhia.Aerea,Codigo.Tipo.Linha,Partida.Prevista,Partida.Real,Chegada.Prevista,Chegada.Real,Situacao.Voo,Codigo.Justificativa,Aeroporto.Origem,...,Estado.Origem,Pais.Origem,Aeroporto.Destino,Cidade.Destino,Estado.Destino,Pais.Destino,LongDest,LatDest,LongOrig,LatOrig
172241,UAL - 129,UNITED AIRLINES,Internacional,2015-12-27T01:25:00Z,2015-12-27T01:25:00Z,2015-12-27T11:19:00Z,2015-12-27T11:19:00Z,Realizado,NaN,Houston,...,N/I,Estados Unidos,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.81341,-95.336783,29.99022
172242,UAL - 129,UNITED AIRLINES,Internacional,2015-12-05T01:25:00Z,2015-12-05T01:21:00Z,2015-12-05T11:19:00Z,2015-12-05T10:48:00Z,Realizado,ATRASOS NAO ESPECIFICOS - OUTROS,Houston,...,N/I,Estados Unidos,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.81341,-95.336783,29.99022
172243,UAL - 129,UNITED AIRLINES,Internacional,2015-12-09T01:25:00Z,2015-12-09T01:25:00Z,2015-12-09T11:19:00Z,2015-12-09T11:19:00Z,Realizado,NaN,Houston,...,N/I,Estados Unidos,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.81341,-95.336783,29.99022

In [19]:
ddf.info(memory_usage=True)

<class 'dask.dataframe.core.DataFrame'>
Columns: 21 entries, Voos to LatOrig
dtypes: object(17), float64(4)
memory usage: 407.4 MB

In [20]:
ddf.describe()

Dask DataFrame Structure:
              LongDest  LatDest LongOrig  LatOrig
npartitions=1
               float64  float64  float64  float64
                   ...      ...      ...      ...
Dask Name: describe-numeric, 248 tasks

### 4.2 Qual a Companhia que fez mas Vôos ?

In [ ]:
df('Companhia_Aerea').value_counts()

In [ ]:
## dASK
ddf('Companhia_Aerea').value_counts().compute()

### 4.4 Mostre a Companhia e a Cidade Destino Ordenados pela Quantidade de Vôos cancelados

Udando Pandas

In [ ]:
df.columns

In [ ]:
voos_cancelados = df['Situacao.Voo']=='Cancelado'

In [ ]:
### Voos da Azul em Campinas
voos_azul_campinas = (df['Companhia.Aerea'] == 'AZUL') & df(['Cidade.Destino'] == 'Capinas')

Usando DASK

In [10]:
ddf.columns

Index(['Voos', 'Companhia.Aerea', 'Codigo.Tipo.Linha', 'Partida.Prevista',
       'Partida.Real', 'Chegada.Prevista', 'Chegada.Real', 'Situacao.Voo',
       'Codigo.Justificativa', 'Aeroporto.Origem', 'Cidade.Origem',
       'Estado.Origem', 'Pais.Origem', 'Aeroporto.Destino', 'Cidade.Destino',
       'Estado.Destino', 'Pais.Destino', 'LongDest', 'LatDest', 'LongOrig',
       'LatOrig'],
      dtype='object')

In [15]:
voos_cancelados = ddf['Situacao.Voo']=='Cancelado'

In [16]:
voos_cancelados

Dask Series Structure:
npartitions=11
    bool
     ...
    ...
     ...
     ...
Name: Situacao.Voo, dtype: bool
Dask Name: eq, 33 tasks

In [18]:
ddf[voos_cancelados]

Dask DataFrame Structure:
                  Voos Companhia.Aerea Codigo.Tipo.Linha Partida.Prevista Partida.Real Chegada.Prevista Chegada.Real Situacao.Voo Codigo.Justificativa Aeroporto.Origem Cidade.Origem Estado.Origem Pais.Origem Aeroporto.Destino Cidade.Destino Estado.Destino Pais.Destino LongDest  LatDest LongOrig  LatOrig
npartitions=11
                object          object            object           object       object           object       object       object               object           object        object        object      object            object         object         object       object  float64  float64  float64  float64
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
...                ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
Dask Name: getitem, 44 tasks

In [19]:
#voos_cancelados = ddf['Situacao.Voo']=='Cancelado'
ddf[voos_cancelados].groupby(['Companhia.Aerea','Cidade.Destino']).agg({'Voos':'count'}).compute().sort_values('Voos',ascending=False)

                                                                    Voos
Companhia.Aerea                                  Cidade.Destino
AZUL                                             Campinas          21203
GOL                                              Rio De Janeiro    16377
                                                 Guarulhos         15544
                                                 Brasilia          11384
AZUL                                             Confins            8606
...                                                                  ...
EMIRATES                                         Buenos Aires          1
TURKISH AIRLINES INC.                            Istanbul/Ataturk      1
EMPRESA DE TRANSPORTES AEREOS DE CABO VERDE S.A. Cabo Verde            1
SETE                                             Macapa                1
COPA -COMPANIA PANAMENA DE AVIACION              Recife                1

[505 rows x 1 columns]

### 4.5 Ordenação de Dados

ddf.set_index('Companhia.Aerea')

In [24]:
ddf.set_index('Companhia.Aerea')

Dask DataFrame Structure:
                         Voos Codigo.Tipo.Linha Partida.Prevista Partida.Real Chegada.Prevista Chegada.Real Situacao.Voo Codigo.Justificativa Aeroporto.Origem Cidade.Origem Estado.Origem Pais.Origem Aeroporto.Destino Cidade.Destino Estado.Destino Pais.Destino LongDest  LatDest LongOrig  LatOrig
npartitions=11
AEROLINEAS ARGENTINAS  object            object           object       object           object       object       object               object           object        object        object      object            object         object         object       object  float64  float64  float64  float64
AIR CHINA                 ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
...                       ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
TAP AIR PORTUGAL          ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
US AIRWAYS INC.           ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
Dask Name: sort_index, 90 tasks

In [25]:
ddf

Dask DataFrame Structure:
                  Voos Companhia.Aerea Codigo.Tipo.Linha Partida.Prevista Partida.Real Chegada.Prevista Chegada.Real Situacao.Voo Codigo.Justificativa Aeroporto.Origem Cidade.Origem Estado.Origem Pais.Origem Aeroporto.Destino Cidade.Destino Estado.Destino Pais.Destino LongDest  LatDest LongOrig  LatOrig
npartitions=11
                object          object            object           object       object           object       object       object               object           object        object        object      object            object         object         object       object  float64  float64  float64  float64
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
...                ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
                   ...             ...               ...              ...          ...              ...          ...          ...                  ...              ...           ...           ...         ...               ...            ...            ...          ...      ...      ...      ...      ...
Dask Name: read-csv, 11 tasks

In [23]:
ddf.compute().sort_values('Companhia.Aerea').head(10)

,Voos,Companhia.Aerea,Codigo.Tipo.Linha,Partida.Prevista,Partida.Real,Chegada.Prevista,Chegada.Real,Situacao.Voo,Codigo.Justificativa,Aeroporto.Origem,...,Estado.Origem,Pais.Origem,Aeroporto.Destino,Cidade.Destino,Estado.Destino,Pais.Destino,LongDest,LatDest,LongOrig,LatOrig
205061,ARG - 1292,AEROLINEAS ARGENTINAS,Internacional,2016-09-28T06:20:00Z,2016-09-28T06:20:00Z,2016-09-28T09:30:00Z,2016-09-28T09:30:00Z,Realizado,NaN,Buenos Aires/Aeroparque,...,N/I,Argentina,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.813410,-58.536759,-34.816662
7979,ARG - 1251,AEROLINEAS ARGENTINAS,Internacional,2016-06-23T17:30:00Z,2016-06-23T17:30:00Z,2016-06-23T20:50:00Z,2016-06-23T20:50:00Z,Realizado,NaN,Aeroporto Internacional Do Rio De Janeiro/Galeao,...,RJ,Brasil,Buenos Aires,Buenos Aires,N/I,Argentina,-58.534828,-34.815004,-43.249423,-22.813410
7980,ARG - 1251,AEROLINEAS ARGENTINAS,Internacional,2016-06-02T17:30:00Z,2016-06-02T17:30:00Z,2016-06-02T20:50:00Z,2016-06-02T20:50:00Z,Realizado,NaN,Aeroporto Internacional Do Rio De Janeiro/Galeao,...,RJ,Brasil,Buenos Aires,Buenos Aires,N/I,Argentina,-58.534828,-34.815004,-43.249423,-22.813410
7985,ARG - 1251,AEROLINEAS ARGENTINAS,Internacional,2016-06-22T17:30:00Z,2016-06-22T17:30:00Z,2016-06-22T20:50:00Z,2016-06-22T20:50:00Z,Realizado,NaN,Aeroporto Internacional Do Rio De Janeiro/Galeao,...,RJ,Brasil,Buenos Aires,Buenos Aires,N/I,Argentina,-58.534828,-34.815004,-43.249423,-22.813410
112827,ARG - 1292,AEROLINEAS ARGENTINAS,Internacional,2015-04-14T06:40:00Z,2015-04-14T06:40:00Z,2015-04-14T09:48:00Z,2015-04-14T09:48:00Z,Realizado,NaN,Buenos Aires/Aeroparque,...,N/I,Argentina,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.813410,-58.536759,-34.816662
112828,ARG - 1292,AEROLINEAS ARGENTINAS,Internacional,2015-04-15T06:40:00Z,2015-04-15T06:40:00Z,2015-04-15T09:48:00Z,2015-04-15T09:48:00Z,Realizado,NaN,Buenos Aires/Aeroparque,...,N/I,Argentina,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.813410,-58.536759,-34.816662
112829,ARG - 1292,AEROLINEAS ARGENTINAS,Internacional,2015-04-27T06:40:00Z,2015-04-27T06:40:00Z,2015-04-27T09:48:00Z,2015-04-27T09:48:00Z,Realizado,NaN,Buenos Aires/Aeroparque,...,N/I,Argentina,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.813410,-58.536759,-34.816662
112831,ARG - 1292,AEROLINEAS ARGENTINAS,Internacional,2015-04-18T06:40:00Z,2015-04-18T06:40:00Z,2015-04-18T09:48:00Z,2015-04-18T09:48:00Z,Realizado,NaN,Buenos Aires/Aeroparque,...,N/I,Argentina,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.813410,-58.536759,-34.816662
112833,ARG - 1292,AEROLINEAS ARGENTINAS,Internacional,2015-04-10T06:40:00Z,2015-04-10T06:40:00Z,2015-04-10T09:48:00Z,2015-04-10T09:48:00Z,Realizado,NaN,Buenos Aires/Aeroparque,...,N/I,Argentina,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.813410,-58.536759,-34.816662
112835,ARG - 1292,AEROLINEAS ARGENTINAS,Internacional,2015-04-20T06:40:00Z,2015-04-20T06:40:00Z,2015-04-20T09:48:00Z,2015-04-20T09:48:00Z,Realizado,NaN,Buenos Aires/Aeroparque,...,N/I,Argentina,Aeroporto Internacional Do Rio De Janeiro/Galeao,Rio De Janeiro,RJ,Brasil,-43.249423,-22.813410,-58.536759,-34.816662